### ISSUE TITLE
Ignore a non-existent module as it is included in the webpage

### ISSUE THREAD

**Issue by sz3lbi** [pboymt/userscript-typescript-template#1]
Hello,
I am using your template to generate a UserScript from the TypeScript code and I would like to use a module provided by the webpage that the UserScript will run at. The script is already included there, so there won't be any problem to access it.  
Now, the `webpack` won't compile the script as it gives the error: `TS2304: Cannot find name 'Timing'.`  
Is there any possibility to make the compiler think that everything is okay and compile the code? Or I have to copy that code and include in my script?  
Thanks.

**Comment by pboymt** [comment]
Timing is a name of module?

**Comment by pboymt** [comment]
You can check the repo [gscholar-title-translator](https://github.com/pboymt/gscholar-title-translator) build from this template.

**Comment by sz3lbi** [comment]
In the webpage, there is the `game.js` file imported which contains the object named `Timing`. And I would like to run a method from this object like: `Timing.getCurrentServerTime()`.

**Comment by sz3lbi** [comment]
The problem is that, depending on the world you are playing on, the url to the file differs a bit. In the other case I could just require it inside my script.

**Comment by pboymt** [comment]
> In the webpage, there is the `game.js` file imported which contains the object named `Timing`. And I would like to run a method from this object like: `Timing.getCurrentServerTime()`.

If it comes from the source page, you need to check how Tampermonkey's document references these contents. If this is a global object, I think you can try using unsafeWindow object.

**Comment by pboymt** [comment]
You can define global objects through the type definition file.

**Comment by sz3lbi** [comment]
I have created the `globals.d.ts` file in the `src` directory with content as following:
```typescript
interface Window {
    unsafeWindow: any;
}
```
I have also added `unsafeWindow` in the `grant` property in the `package.json` file.
```json
"userscript": {
    //...
    "grant": [
      "unsafeWindow"
    ],
  }
```

And when I am using the `unsafeWindow` property to access the `Timing` object, everything works fine.
```typescript
window.unsafeWindow.Timing.getCurrentServerTime()
```

Thank you for your help.
